# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculate normalised S matrix
#' @param D list of data matrices
#' @param ncols number of columns of input matrices
#' @export
calcNormS <- function(D, ncols) {
    .Call('_hogsvdR_calcNormS', PACKAGE = 'hogsvdR', D, ncols)
}

