# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculate normalised S matrix
#' @param D list of data matrices
#' @param ncols number of columns of input matrices
#' @param nthreads number of omp threads, 0 for max
#' @export
calcNormS <- function(D, ncols, nthreads = 0L, verbose = TRUE) {
    .Call('_hogsvdR_calcNormS', PACKAGE = 'hogsvdR', D, ncols, nthreads, verbose)
}

